spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qsps?characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    cache: false
  messages:
    basename: validation
  resources:
    static-locations:
    - classpath:static  
server:
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat
