spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qsps?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat
